version: '3'

volumes:
  allure-docker-service:
    driver: local

services:
  allure-docker-service:
    build:
      context: ../allure-docker-service
      dockerfile: docker-custom/Dockerfile.bionic-custom
      args:
        ALLURE_RELEASE: "2.13.4"
    environment:
      DEV_MODE: 1
      CHECK_RESULTS_EVERY_SECONDS: 5
      KEEP_HISTORY: 1
      KEEP_HISTORY_LATEST: 5
    ports:
      - "5050:5050"
    volumes:
      - ./.data/allure-docker-service/allure-results:/app/allure-results
